### ISSUE TITLE
您好，请问您这个程序所用的喷墨喷头是啥喷头呀？

### ISSUE THREAD

**Issue by sadsaadsd** [YanMing-lxb/Inkjet_Printing_System#1]
您好，请问您这个程序所用的喷墨喷头是啥喷头呀？

**Comment by YanMing-lxb** [comment]
惭愧，这个软件只是画出来图，喷头啥样我也不知道，抱歉啊

**Comment by sadsaadsd** [comment]
那这个软件有切片功能吗？还是说只是显示显示三维模型呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月16日(周四) 晚上11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YanMing-lxb/Inkjet_Printing_System] 您好，请问您这个程序所用的喷墨喷头是啥喷头呀？ (Issue #1)




 
惭愧，这个软件只是画出来图，喷头啥样我也不知道，抱歉啊

**Comment by YanMing-lxb** [comment]
只是显示三维模型

**Comment by sadsaadsd** [comment]
好的好的，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月17日(周五) 晚上8:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YanMing-lxb/Inkjet_Printing_System] 您好，请问您这个程序所用的喷墨喷头是啥喷头呀？ (Issue #1)




 
只是显示三维模型
